name: Git Continious Integration Unit Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install GoogleTest from source
      run: |
        git clone https://github.com/google/googletest.git
        cd googletest
        cmake -B build
        cmake --build build
        sudo cmake --install build

    - name: make
      run: make
    - name: make coverage
      run: make coverage
